### ISSUE TITLE
Set up reactive (non-user interaction) events that use the ACSS conditionals (the "observe" event)

### ISSUE THREAD

**Issue by dragontheory** [Active-CSS/active-css#184]
Thank you for your hard work! 

I am attempting to emulate native CSS `:has()` behavior with the below rule but it is not working. Seems pretty straight forward. What am I missing? 

Passively (without end-user interaction) watch for: 

- Rule = TRUE
Add the `.loading` class to `<body>`. 
- Rule = FALSE 
Remove `.loading` class from `<body>`. 

```
#component div:if-empty {
    body {add-class: '.loading';}
}
```
[CodePen here](https://codepen.io/dragontheory/pen/VwWOJqd)

Please advise. 

Thanks again!

**Comment by bob2517** [comment]
Hi there! ACSS doesn't work passively. It only works in response to events. That's the issue.... you need to have a :click or something at the end of each event selector. Check out the documentatiom on event selectors. Hope that helps.

Regards,
Rob

⁣Sent from BlueMail ​

**Comment by bob2517** [comment]
Something like this as a workaround should work, but it isn't - I'll have to check this out after work this evening when I get more time.

```
div:draw {
  @if inner-html(#content div "") {
	 		trigger: populateDiv;
	}
}
div:populateDiv {
	body {
		add-class: loaded;
	}
}
```

**Comment by bob2517** [comment]
Just a note on the initial thought before I shoot off to work - as the check should be passive the demanded functionality should be a part of the regular CSS spec rather than in ACSS which is purely user-initiated event-driven. The alternative would be adding some sort of JS observer to the div.

**Comment by dragontheory** [comment]
We are all busy. Thank you very much for your quick response!

I agree with and share your passion for CSS and the benefits of decoupling the UI from the data (Separation of Concerns).

This is most likely "delusions of grandeur", but I am attempting to take it the "last mile" by leveraging CSS's unique "plug-n-play" nature to passively watch for (without expensive polling) and react to (without end-user interaction) virtually any changes on the DOM, thereby COMPLETELY decoupling the UI from the data.

In other words, the UI doesn't react to end-user interactions. The UI reacts to the DATA being loaded from end-user interactions. Button clicks no longer control the UI. They simply fetch data.

Integration could be as simple as a list (data-schema/config file?) of anticipated selectors, text strings, and or pseudo element conditionals.

The UI would operate independent of various JS frameworks (or any other data delivery system) and intelligently passively watch for data points to show up in the DOM.

And since it lives and operates in the browser, no compiling or other tools are necessary. Back-end DEVs only worry about data. Front end DEVs only worry about UI.

Revolutionizing web development as we know it.

Not sure how far I can go, but it requires the use of, as of yet browser supported, CSS functionality (such as parent selectors and `:has()`), **_which your good work provides_**.

So, is there some way, using your script, to emulate passively watching for and reacting to CSS/ACSS rules as they become true and false? 

For example, watch for all form elements within a given `<div>`​ to not be `:empty()` and then add one or more class(es) to `<body>`​ and remove those classes when that rule becomes false. 

Thanks again.

**Comment by bob2517** [comment]
Yes, I think you're onto something there. I've had a good think about it and it should be possible in a relatively performant way. I'll have time to look at it properly at the weekend. It's looking very possible though.

I did send some emails to this issue yesterday from my phone, but I don't think they arrived. The fix for the initial problem would be basically just adding a draw event and changing the conditional to a more appropriate one:

```
#component div:if-inner-html(self ""):draw {
    body {add-class: '.loading';}
}
```

But again - I've got to rush off to work so I don't know if that actually works or not...

**Comment by bob2517** [comment]
I'm very glad it worked! I dunno why I was getting so complicated before...

> .loading class is added to the <body> - assuming the init is on page load?

Yes, on first loading of the page each element gets the draw event checked and ran if it is present. Point 3 on the initialization docs page:
https://activecss.org/manual/init-events.html

I'm getting a bit excited about this new feature you've suggested. I can't actually start any coding on it until the weekend, but I've basically worked out the code in my head for it, assuming that it's even possible, which I think it is. There could be major performance hits if people get crazy with trying to observe a lot (eg. someone sets up an observer CSS rule that triggers an event over menu items that get a class added every time the mouse goes over the menu item so observer events happen 20 times a second), so it needs to be as quick as it can be and I think I've worked out the fastest method. I won't know until it's coded how much of an impact it's going to have on perfomance. But performance will only be affected if the observing method is actually used in the config, so there's no harm in experimenting with it.

Just to save some time on getting the code set up for testing, I'm going to add a new event ":observe", which will be on the end of each of these - for now only (probably) - like:

```
#component div:if-inner-html(self ""):observe {
}
```

... but only while testing is happening on it. Once we are sure it's working then I'll remove the ":observe" part and tackle the next issue of trying to get it living alongside regular CSS. So it will ultimately look like:

```
#component div:if-inner-html(self "") {
}
```

(The "if-" prefix is there just so it doesn't clash with CSS in the future when new native pseudo-selectors get added to the spec.)

Internally though (I'm noting to self on this now) - we'll insert the ":observe" event onto observing events so it slots nicely into the internal config array where all the config lives.

**Comment by bob2517** [comment]
And obviously there's reactive variables in ACSS, which sort of does it, but not at a DOM level with conditionals...

**Comment by bob2517** [comment]
Into the "talking to myself" stage on development now, where I'll be putting things into the ticket which is relevant as it comes up - it doesn't require commenting on by anyone particularly - it's just better for me to write stuff down rather than keep it all in my head clogging up my thought process. Random comments start now...

For the record, I think that currently the only "reactive" events in ACSS are these:

draw
disconnectCallback
adoptedCallback
attributeChangedCallback
beforeComponentOpen
componentOpen

Each one has its own handling in the core. And each one passes through the _handleEvents function to get their conditionals handled.

To these are being added the single "observe" event, which will be based on mutations covering all element mutation scenarios and thereby should all follow a single consistent observe rule on mutations, hopefully.

**Comment by bob2517** [comment]
Actually... that's a good point on initialisation. Do we run through all the observe events at the initial draw stage? I guess so. They'll either pass or fail.
It makes me wonder though if all the draw events should run before the init event, as the draw event is also a reactive event, albeit very specialised.
I need to look at this - preInit should be used for variable type setups. init should be used at initialization stage prior to any DOM stuff. Then observe, then draw, then scroll. There could also be a "postInit" event added to the end maybe. I dunno. I'll slot in the observe events to run prior to draw for now.

After that the observe event will run on a per element basis whenever something changes in the DOM.

**Comment by bob2517** [comment]
Basically we need to run through all the observe events on each element at the start, otherwise we miss their first appearance on the page, which is the first reactive event, and we can't trap that until after the fact, as the core doesn't kick in until after the page is already drawn. Hence we need to run through observe events on page load to account for the first DOM change, which is actually just the DOM appearing on the empty page.

**Comment by bob2517** [comment]
This also implies that observe events should also happen prior to draw events at the point of dynamic rendering the element on the page. So I'll put the observe event there too.

Which comes first, the draw event or the observe event?

Which would make more sense? Do we run the draw event and then manually trigger the observe event or do we let the fact that the element has appeared in the DOM trigger the observe event?

I might the draw event out of where it is now, and turn it into a mutation handling.

Should it run prior to the observe event? Probably, I think. Prior to the draw, it doesn't really exist, ie. it hasn't been "drawn" per the draw event.

Ok - I'll move the draw event into the mutation area and get this running before then checking for the observe event.

So, steps to implementation:

1. Run the observe event on all elements after the draw events get run at initialisation time.
2. Get the observe event working so we can see that the concept works.
3. Put in a draw event to run prior to the observe event, so that should give me two draw events happening at this stage.
4. Remove the "manual" draw event calls.

That should be it.

The last step before release would be adding any useful conditionals (DOM change pseudo-selectors) that might be missing.

**Comment by bob2517** [comment]
There will be a double observe event if the draw event triggers a change to the element itself which triggers a separate observe event prior to the general observe event check. Not sure of the full implications of that yet, other than the fact there will be a performance hit. Will find out soon enough.

**Comment by bob2517** [comment]
I just hope that the performance hit isn't too big. That is the only concern I have with all this...

**Comment by bob2517** [comment]
Doh, the test code was wrong:

```
#addClass:click {
	body { add-class: .helloWorld; }
}

#removeClass:click {
	body { remove-class: .helloWorld; }
}

body:if-has-class(self .helloWorld):observe {
	p { render: "The helloWorld class is now on the body tag"; }
}

body:not-if-has-class(self .helloWorld):observe {
	p { render: "The body tag does not have the helloWorld tag"; }
}
```

I've got a basic implementation in place which works. There's not a lot of code there and it looks too simple - needs more testing, like when things get removed, added, blah. Test code works though, which is nice.

**Comment by bob2517** [comment]
Yeah - just spotted that it probably won't work as expected with components. Will test the speed first, without my console logs, just to see the performance hit.

**Comment by bob2517** [comment]
I'm not seeing any performance hit yet, but it's possible I need to set up more stuff. Will find out shortly.

**Comment by bob2517** [comment]
I'm going to get food and call it a night. All looking good so far, although the ease of implementation does worry me a little bit. I should have something up on the branch by the end of tomorrow which can be tested in earnest...

**Comment by bob2517** [comment]
I just realised my test case was over-engineered. The actual code you need is this:

```
#addClass:click {
	body { add-class: .helloWorld; }
}

#removeClass:click {
	body { remove-class: .helloWorld; }
}

body.helloWorld:observe {
	p { render: "The helloWorld class is now on the body tag"; }
}

body:not(.helloWorld):observe {
	p { render: "The body tag does not have the helloWorld tag"; }
}
```

Basically just straight CSS with the observe event - and it actually works.

I think based on this that the "observe" event should stay as permanent syntax.

Boom! Problem of differentiating between ACSS and CSS... SOLVED!

**Comment by bob2517** [comment]
More to do to get this theory working - currently the observe event will fire whenever there is a change to the element, regardless of what that change is, if it has the hellowWorld class. This isn't what we want. The example implies that whenever the helloWorld class is added or removed then the event runs.

I think the solution lies in the use of the event itself - we need a more flexible way to determine when an element will react. More events probably. Will ponder and resume tomorrow.

This works great as an event that triggers every time an element changes in some way though, so it's definitely a start.

**Comment by bob2517** [comment]
Yes, like the DOM has lots of user-initiated events, we need lots of different reactive events. I'm pretty sure that is the answer. Just need to work out what those events should be...

**Comment by bob2517** [comment]
Hang on a sec... I think I may have cracked it. Will do some coding.

**Comment by bob2517** [comment]
Going to do the internal conditional state tracking method. That is the way, I have spoken. I don't know at this point if more syntax is needed for the developer, but this is the next logical implementation step. Will see shortly if more is needed for the logic.

**Comment by bob2517** [comment]
The observe event needs to be able to run on an element that isn't getting observed, like here:

```
p:if-inner-html(#contentArea ""):observe {
    render: "Content area is empty";
}
```

The mutation happens on the #contentArea - not the p tag.

This an important point. It means that any mutation event on the page needs to be checked against all appropriate observe events to check if something needs to update. This is the potential performance hit.

**Comment by bob2517** [comment]
Once the logic is set up for this, then the intersection code can follow the same code logic.

**Comment by bob2517** [comment]
This is similar to how the main core event handling works and the performance is just fine, so hopefully this won't add too much overhead.

**Comment by bob2517** [comment]
Ideally the code should be run in the _handleEvents script so we don't get double checking of conditionals, but I'm going to keep it separate for now so I can see what can be merged in and what can't - it may need a fresh event handling script to stop things getting complicated in the core.

**Comment by bob2517** [comment]
I think this method will be ok in terms of performance. Mutations get grouped together before hitting the observer function. I just need to know if there was a change - there may have been a hundred changes but I only need to run the handler once, so that should mean performance hits are kept to a minimum.

**Comment by bob2517** [comment]
We've also got custom selectors that can have conditionals, like this:

```
~myEvent:if-inner-html(#contentArea ""):observe {
    p {
        render: "The content area is empty.";
    }
}
```

Should this be able to be observed? I don't see why not. It just needs the ACSS conditionals checked.

**Comment by bob2517** [comment]
Note to self: shadow DOM component mutations may or may not need a separate mutation observer, if that's possible. They shouldn't react to document level mutations, otherwise it defeats the point of the shadow DOM. There's already a way to tie shadow DOM changes to host attributes and that should be the only observable factor as that matches the way the browser works. So observables should be limited to document or shadow DOM scope. The same goes for private event scoped ACSS components, but will tackle these one at a time later on.

**Comment by bob2517** [comment]
So to recap, these two examples work as expected currently, ie. they only change when there has been an actual change, and once they are changed, they don't run again until there is another change to that specific event criteria:

Observe event acting on self:

```
#addClass:click {
    body { add-class: .helloWorld; }
}

#removeClass:click {
    body { remove-class: .helloWorld; }
}

body.helloWorld:observe {
    p { render: "The helloWorld class is now on the body tag"; }
}

body:not(.helloWorld):observe {
    p { render: "The body tag does not have the helloWorld class"; }
}
```

Observe event occuring which is reliant on a change elsewhere in the DOM:
```
#addClass:click {
    body { add-class: .helloWorld; }
}

#removeClass:click {
    body { remove-class: .helloWorld; }
}

p:if-has-class(body .helloWorld):observe {
    render: "The helloWorld class is now on the body tag";
}

p:not-if-has-class(body .helloWorld):observe {
    render: "The body tag does not have the helloWorld class";
}
```

**Comment by bob2517** [comment]
You're going to have to take my word on it that these work for now :)

**Comment by bob2517** [comment]
That works on a change after the DOM has drawn. Just need to set it up so that observe events are checked at initialisation time.

**Comment by bob2517** [comment]
That's working. I think I'm going to do a commit and then work on the rest separately. This implementation covers all use cases that have nothing to do with the shadow DOM or ACSS components.

**Comment by bob2517** [comment]
It seems to be working well in shadow DOMs and ACSS components, but it needs optimising which I'm doing now. It's probably going to be fine, but I can see a way to speed it up.

As part of testing this for components, I'm going to convert a bunch of concept examples to use the "observe" event instead of the current method. As well as seeing what differences there are to coding in this manner, and if it feels easier to code in this way, or that it's easier to read, it should also verify that variable scoping and event scoping still works as it should. It should also bring up anything that might be missing from the way it works at the moment.

Note to self: there's things like "for" loops, await and event loop "parallel" functionality to test with this, so make sure everything is covered.

Once these steps are done, the integration for the intersection observer stuff should be a doddle, once I've understood what it's actually supposed to do.

**Comment by bob2517** [comment]
Note to self: Need to look at custom selectors (eg. "~doSomething:please {}") set up inside components, as IIRC the scoping is implemented there and will need to be handled properly if so. That will not work currently if that is the case as there's no accounting for that in the code yet. That will need to be put in there if custom selectors follow the scoping rules, but I can't recall off the top of my head if that is the case or not.

**Comment by bob2517** [comment]
More of a later thing, but it would be good to detect CSS animation ending too and be able to code that with an observe event checking the element with a custom conditional that checks for animation ending. Currently CSS animations that end do not trigger any mutation events, because there aren't any being made to the DOM.

**Comment by bob2517** [comment]
For the record, I think I've sorted out a memory leak which is related to shadow DOM clean-up. Basically internal pointers were not cleaning up on shadow DOM removal, but that should be fixed now.

**Comment by bob2517** [comment]
Input change event needs testing in shadow DOMs - the code is in place for this, just a test is needed.

**Comment by bob2517** [comment]
For shadow DOMs, as well as observing inside the shadow DOM, which it does currently offline, it is also going to be necessary to be able to observe the host element for attribute changes. Currently this works with reactive variables but I don't think it's going to work with the observe event, because mutations are happening outside the shadow DOM and reactions are contained to the DOM they are reacting to. So a special case is needed to run the observe event when the attribute of the host changes.

Note to self: This can probably be implemented at the stage of create-element, which is the method needed to pass attributes from the host element to its inner Shadow DOM. Just set up a separate observer or something for that which ties into the main bunch. It doesn't need anything fancy.

**Comment by bob2517** [comment]
After this, rewrite the shadow DOM events observe concept example so instead of setting a class inside the component, it just sets something in the outer host element to monitor the state inside. That would be cool. It would mean that components could be reset or changed by setting attributes on the host element and the inner shadow DOM component would react accordingly. That should get a separate concept example made up.

**Comment by bob2517** [comment]
When it gets to point 4 (or 5), mark this issue as complete on branch and start a new one as this one is getting rather large.

**Comment by bob2517** [comment]
Point 1 is done and is now on the branch, along with the earlier addition to detect input field changes which I forgot to push up.

**Comment by bob2517** [comment]
Note to self: Rewrite the todo example using the observe event - it could reduce the amount of code needed to do the same thing.

**Comment by bob2517** [comment]
For the sake of getting the new release out, I'm marking this issue - the observe event specifically - as ready for release pending anything that comes up while I'm getting the docs ready for the new release and running further tests.

Anything mentioned in here that isn't related to expanding the observe event will henceforth get a new issue.

**Comment by bob2517** [comment]
Closing in preparation for release. Oooohhhh!
