### ISSUE TITLE
Issue with new combinators

### ISSUE THREAD

**Issue by bob2517-whiteline** [Active-CSS/active-css#289]
Something's busted on this - not working on a specific project - investigate. Failing scenario basic "& < div".

**Comment by bob2517** [comment]
Repeatable - face palm.

**Comment by bob2517** [comment]
Fixed on the 2.11.1 branch for combinators that don't have any other special ACSS combinators following it, so that should be most use cases.

Need to set up some more tests for these, so I won't do a release until that is done. Progress will be spotty during the week.

Meanwhile, if anyone sees any errors, let me know in this issue and it will save me hunting for them.

**Comment by bob2517** [comment]
Better fix added to branch. Still tests to do though.

**Comment by bob2517** [comment]
Closing pending release.
