### ISSUE TITLE
Add "pages" option to console-log

### ISSUE THREAD

**Issue by bob2517-whiteline** [Active-CSS/active-css#311]
Need a way to view the @pages settings in the config via debug. Add this and get it displaying the @pages object:
```
console-log: pages;
```

**Comment by bob2517** [comment]
Looking at the code, there is a wildcard option in @pages that I've never used in production, so it's never been battle-tested. It needs re-evaluating and testing. It's only useful in the scenario where all the references needed to switch pages is in the element itself rather than pages, which has never been practical for a website with a back-end that allows any user to add a link, as you don't expect them to go into the code in tinymce or whatever to add the relevant page switching attributes - that would more practically be done from a database, from page details that were stored in a table, which is the way I always do it. Page wildcards need a different application - like static type of scenario where the link tags are hard-coded, so it needs a proper SPA example set up for testing.

If that works, there is a separate page wildcard array that could be output as part of this issue. For now though, non-wildcard page details can be viewed with: ```console-log: pages;```

**Comment by bob2517** [comment]
Closing in preparation for release.
